"""Small, dependency-free canonical models for persisted pipeline state.

The models deliberately store only JSON-compatible values.  Heavy data and
uploaded files belong in the artifact repository and are referred to by opaque
IDs from these objects.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

PROJECT_SCHEMA_VERSION = 1
ARTIFACT_MANIFEST_SCHEMA_VERSION = 1

JsonObject = dict[str, Any]


def utc_now_iso() -> str:
    """Return an RFC 3339 compatible UTC timestamp."""

    return datetime.now(UTC).isoformat()


def _mapping(value: Mapping[str, Any] | None) -> JsonObject:
    return dict(value or {})


class PipelineStageStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass(frozen=True, slots=True)
class PipelineStageResult:
    """Persistable outcome of one named pipeline stage."""

    stage: str
    status: PipelineStageStatus
    started_at: str
    finished_at: str | None = None
    artifact_ids: tuple[str, ...] = ()
    metrics: Mapping[str, Any] = field(default_factory=dict)
    message: str | None = None

    def __post_init__(self) -> None:
        if not self.stage.strip():
            raise ValueError("Pipeline stage name cannot be empty")
        object.__setattr__(self, "status", PipelineStageStatus(self.status))
        object.__setattr__(self, "artifact_ids", tuple(self.artifact_ids))
        object.__setattr__(self, "metrics", _mapping(self.metrics))

    def to_dict(self) -> JsonObject:
        return {
            "stage": self.stage,
            "status": self.status.value,
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "artifact_ids": list(self.artifact_ids),
            "metrics": dict(self.metrics),
            "message": self.message,
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> PipelineStageResult:
        return cls(
            stage=str(value["stage"]),
            status=PipelineStageStatus(value["status"]),
            started_at=str(value["started_at"]),
            finished_at=(
                str(value["finished_at"]) if value.get("finished_at") is not None else None
            ),
            artifact_ids=tuple(str(item) for item in value.get("artifact_ids", ())),
            metrics=_mapping(value.get("metrics")),
            message=str(value["message"]) if value.get("message") is not None else None,
        )


@dataclass(frozen=True, slots=True)
class ArtifactRecord:
    """Metadata for one project-owned file.

    ``relative_path`` is generated by the repository.  It is never accepted as
    an upload path or exposed as an authority-bearing client input.
    """

    artifact_id: str
    kind: str
    relative_path: str
    sha256: str
    size_bytes: int
    created_at: str
    original_name: str | None = None
    media_type: str | None = None
    immutable: bool = True
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.kind.strip():
            raise ValueError("Artifact kind cannot be empty")
        if self.size_bytes < 0:
            raise ValueError("Artifact size cannot be negative")
        object.__setattr__(self, "metadata", _mapping(self.metadata))

    def to_dict(self) -> JsonObject:
        return {
            "artifact_id": self.artifact_id,
            "kind": self.kind,
            "relative_path": self.relative_path,
            "sha256": self.sha256,
            "size_bytes": self.size_bytes,
            "created_at": self.created_at,
            "original_name": self.original_name,
            "media_type": self.media_type,
            "immutable": self.immutable,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> ArtifactRecord:
        return cls(
            artifact_id=str(value["artifact_id"]),
            kind=str(value["kind"]),
            relative_path=str(value["relative_path"]),
            sha256=str(value["sha256"]),
            size_bytes=int(value["size_bytes"]),
            created_at=str(value["created_at"]),
            original_name=(
                str(value["original_name"]) if value.get("original_name") is not None else None
            ),
            media_type=(str(value["media_type"]) if value.get("media_type") is not None else None),
            immutable=bool(value.get("immutable", True)),
            metadata=_mapping(value.get("metadata")),
        )


@dataclass(frozen=True, slots=True)
class ArtifactManifest:
    """Versioned manifest for one independently reproducible pipeline run."""

    manifest_id: str
    project_id: str
    run_id: str
    created_at: str
    updated_at: str
    artifacts: tuple[ArtifactRecord, ...] = ()
    stages: tuple[PipelineStageResult, ...] = ()
    effective_config_artifact_id: str | None = None
    schema_version: int = ARTIFACT_MANIFEST_SCHEMA_VERSION

    def __post_init__(self) -> None:
        object.__setattr__(self, "artifacts", tuple(self.artifacts))
        object.__setattr__(self, "stages", tuple(self.stages))

    def to_dict(self) -> JsonObject:
        return {
            "schema_version": self.schema_version,
            "manifest_id": self.manifest_id,
            "project_id": self.project_id,
            "run_id": self.run_id,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "effective_config_artifact_id": self.effective_config_artifact_id,
            "artifacts": [artifact.to_dict() for artifact in self.artifacts],
            "stages": [stage.to_dict() for stage in self.stages],
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> ArtifactManifest:
        return cls(
            schema_version=int(value.get("schema_version", 0)),
            manifest_id=str(value["manifest_id"]),
            project_id=str(value["project_id"]),
            run_id=str(value["run_id"]),
            created_at=str(value["created_at"]),
            updated_at=str(value["updated_at"]),
            effective_config_artifact_id=(
                str(value["effective_config_artifact_id"])
                if value.get("effective_config_artifact_id") is not None
                else None
            ),
            artifacts=tuple(ArtifactRecord.from_dict(item) for item in value.get("artifacts", ())),
            stages=tuple(PipelineStageResult.from_dict(item) for item in value.get("stages", ())),
        )


@dataclass(frozen=True, slots=True)
class Project:
    """Top-level persisted project metadata."""

    project_id: str
    created_at: str
    updated_at: str
    title: str = ""
    artist: str = ""
    latest_run_id: str | None = None
    reference_artifact_id: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)
    schema_version: int = PROJECT_SCHEMA_VERSION

    def __post_init__(self) -> None:
        object.__setattr__(self, "metadata", _mapping(self.metadata))

    def to_dict(self) -> JsonObject:
        return {
            "schema_version": self.schema_version,
            "project_id": self.project_id,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "title": self.title,
            "artist": self.artist,
            "latest_run_id": self.latest_run_id,
            "reference_artifact_id": self.reference_artifact_id,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> Project:
        return cls(
            schema_version=int(value.get("schema_version", 0)),
            project_id=str(value["project_id"]),
            created_at=str(value["created_at"]),
            updated_at=str(value["updated_at"]),
            title=str(value.get("title", "")),
            artist=str(value.get("artist", "")),
            latest_run_id=(
                str(value["latest_run_id"]) if value.get("latest_run_id") is not None else None
            ),
            reference_artifact_id=(
                str(value["reference_artifact_id"])
                if value.get("reference_artifact_id") is not None
                else None
            ),
            metadata=_mapping(value.get("metadata")),
        )
