"""Shared safe-path, identifier, and atomic-write storage helpers."""

from __future__ import annotations

import json
import os
import re
import secrets
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any


class StorageError(RuntimeError):
    """Base class for persistence errors."""


class RecordNotFoundError(StorageError):
    """A requested project, run, or artifact does not exist."""


class InvalidIdentifierError(StorageError, ValueError):
    """An external identifier was not generated by this application."""


class SchemaVersionError(StorageError):
    """Persisted data has a schema version this application cannot read."""


class ImmutableArtifactError(StorageError):
    """An operation would replace an immutable artifact or snapshot."""


class ArtifactIntegrityError(StorageError):
    """An artifact no longer matches its registered digest or size."""


_ID_RE = re.compile(r"^(?P<prefix>[a-z][a-z0-9]{1,7})_[0-9a-f]{32}$")


def new_opaque_id(prefix: str) -> str:
    if not re.fullmatch(r"[a-z][a-z0-9]{1,7}", prefix):
        raise ValueError(f"Invalid identifier prefix: {prefix!r}")
    return f"{prefix}_{secrets.token_hex(16)}"


def validate_opaque_id(value: str, prefix: str) -> str:
    match = _ID_RE.fullmatch(value)
    if match is None or match.group("prefix") != prefix:
        raise InvalidIdentifierError(f"Invalid {prefix} identifier")
    return value


def contained_path(root: Path, *parts: str) -> Path:
    """Resolve a path and reject traversal outside ``root``."""

    resolved_root = root.resolve()
    candidate = resolved_root.joinpath(*parts).resolve()
    try:
        candidate.relative_to(resolved_root)
    except ValueError as exc:
        raise StorageError("Resolved path escapes the storage root") from exc
    return candidate


def atomic_write_json(path: Path, value: Mapping[str, Any]) -> None:
    """Durably replace a JSON document without exposing a partial write."""

    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        payload = json.dumps(
            value,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
    except (TypeError, ValueError) as exc:
        raise StorageError(f"Value is not JSON serializable: {exc}") from exc

    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_name = temporary.name
            temporary.write(payload)
            temporary.write("\n")
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, path)
    finally:
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)


def read_json(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as source:
            value = json.load(source)
    except FileNotFoundError as exc:
        raise RecordNotFoundError(f"Record does not exist: {path.name}") from exc
    except (OSError, json.JSONDecodeError) as exc:
        raise StorageError(f"Cannot read persisted record {path.name}: {exc}") from exc
    if not isinstance(value, dict):
        raise StorageError(f"Persisted record {path.name} is not a JSON object")
    return value
